### ISSUE TITLE
Issues in the 1.7.0 package

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/google-benchmark#11]
I've spotted a couple for issues in the submitted 1.7.0 package:

1. We had this discussion on Slack about the library that defined `main()` and my understanding is that the agreement was that we will not duplicate code between the two libraries (even though upstream might be doing so). But looking at the `buildfile`, things still appears to be duplicated:

```
libul{benchmark}: cxx{* -benchmark_main} hxx{*} $pub/$pub_hdrs
lib{benchmark}: libul{benchmark}
lib{benchmark_main}: cxx{benchmark_main} libul{benchmark}
```

Also I am not sure it's a good idea to have a shared library that defined `main()` (the semantics of such a library is non-portable, AFAIC). The old setup where we had only `liba{benchmark_main}` seems more sensible to me.

2. This is problematic:

```
windows_additional_defines =
if($cxx.target.system == 'win32-msvc')
  windows_additional_defines = '-D_CRT_SECURE_NO_WARNINGS'
  
lib{benchmark*}:
{
  cxx.export.poptions += "-I$out_root/include" "-I$src_root/include" $windows_additional_defines
}
```

We should not be disabling warnings in client code like this.

**Comment by Swat-SomeBug** [comment]
> windows_additional_defines =
> if($cxx.target.system == 'win32-msvc')
>   windows_additional_defines = '-D_CRT_SECURE_NO_WARNINGS'

This was only added in following upstream. I will check if the library itself really needs this or not.

Also I am not sure it's a good idea to have a shared library that defined main() (the semantics of such a library is non-portable, AFAIC). The old setup where we had only liba{benchmark_main} seems more sensible to me.

**Comment by Swat-SomeBug** [comment]
Sorry didn’t mean to close

**Comment by Swat-SomeBug** [comment]
> Also I am not sure it's a good idea to have a shared library that defined main() (the semantics of such a library is non-portable, AFAIC). The old setup where we had only liba{benchmark_main} seems more sensible to me.

Moving to the old way makes also sense. The main reason I did it this way is because I could follow upstream more closely. They explicitly export `main`, which means it’s fully supported.
The expectation then from consumers is that the `build2` package also provides this option.

**Comment by boris-kolpackov** [comment]
> The main reason I did it this way is because I could follow upstream more closely. They explicitly export `main`, which means it’s fully supported.

I think we've pretty much established that this upstream plays it pretty loose and often does questionable things (and if they really export `-D_CRT_SECURE_NO_WARNINGS` to the user of the library, then I would be willing to use even stronger terms). So to me "which means it’s fully supported" does not follow at all.
