### ISSUE TITLE
Need to link "shlwapi.lib" when building for Windows

### ISSUE THREAD

**Issue by helmesjo** [build2-packaging/google-benchmark#3]
Hi again! :)

Just tried to build & run my benchmarks (linking `benchmark`) on MSVC and got this:

```
benchmark.lib(sysinfo.lib.obj) : error LNK2019: unresolved external symbol __imp_SHGetValueA referenced in function "double __cdecl benchmark::`anonymous namespace'::GetCPUCyclesPerSecond(enum benchmark::CPUInfo::Scaling)" (?GetCPUCyclesPerSecond@?A0x511b6745@benchmark@@YANW4Scaling@CPUInfo@2@@Z)
```

Adding this when building makes it work (mentioned [here](https://github.com/google/benchmark/blob/847c0069021ade355b7678a305f3ac4e4d6f7e79/README.md#windows-with-cmake)):
`config.cxx.loptions+="/link shlwapi.lib"`

So I guess this should go along with the exported linker flags when building for Windows.

**Comment by helmesjo** [comment]
Also, since `benchmark` [fails to build shared libs on Windows](https://github.com/google/benchmark/issues/639), maybe the README for this should mentioned that it must be imported as a static lib: `import benchmark_libs += google-benchmark%liba{benchmark}`.

**Comment by Swat-SomeBug** [comment]
Hi @helmesjo, thanks for reporting. Yes the package doesn’t build on Windows yet.
I’m currently working on a PR for this.
