### ISSUE TITLE
Few google-benchmark-1.6.0 issues

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/google-benchmark#7]
I've noticed the following issues in the submitted `google-benchmark-1.6.0`:

1. The library name `liba{benchmark-main}` doesn't seem to match upstream's `benchmark_main`. Here is its name in the Debian package, for example:

```
/usr/lib/x86_64-linux-gnu/libbenchmark_main.a
```

It's a good idea to stick to the upstream naming in case people want to use the system-installed version of the library.

2. `bin.lib.version` has no effect for static libraries so it can be dropped for `benchmark_main` (there is also a typo in the `else` block in its target type).

3. Patching `benchmark.h` on the fly during build is not worth the potential issues.

Specifically, an auto-generated public header is a can of worms and requires special defensive measures because while it does not exist, the C/C++ compiler will happily include the same header from another location. The most common example is an older/other version of the library that is installed in a location where the compiler searches by default (e.g., `/usr/include`). In this case the compiler will pick up the old header until the new one gets generated. What happens in the meantime, is anyone's guess (for example, the includer may detect version mismatch and `#error`-out). There are ways to avoid this but they are not worth the complexity where it can be avoided.

So I would suggest that you replace the on-the-fly patching with manual patching. In fact, seeing that you already have all the commands in the `buildfile`, you can just wrap the rule `if false` and enable it when you need to re-generate the patched `benchmark.h` (e.g., when upgrading to the new version of upstream).

Let me know if you would like to fix these issues in a revision (I will hold the current submission in the queue for now).

**Comment by Swat-SomeBug** [comment]
Hi Boris,
Thank you very much for having a look at it.
Yes I will fix this and submit another package revision.

I also agree with manually patching the header.
The solution you propose gives sufficient flexibility for dev and prevents traps for consumers.

Best regards,
Swat
